# Generated by Django 4.1.3 on 2022-11-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordanswer',
            name='keywordofpaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='paa.keywordofpaa'),
        ),
        migrations.CreateModel(
            name='KeyWordVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=500)),
                ('keywordofpaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='paa.keywordofpaa')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordGoogleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('keywordofpaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_images', to='paa.keywordofpaa')),
            ],
        ),
    ]
