# Generated by Django 4.1.3 on 2022-12-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0003_alter_keywordgoogleimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordgoogleimages',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keywordimages',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keywordrelated',
            name='related_search',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='keywordvideos',
            name='video',
            field=models.TextField(),
        ),
    ]
