# Generated by Django 4.1.3 on 2022-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0004_alter_keywordgoogleimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordgoogleimages',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
